### ISSUE TITLE
problème calcul du nombre d'allumage

### ISSUE THREAD

**Issue by sbilloir** [Jahislove/Hargassner#1]
La requête sql utilisé dans **json allumeur .php** n'est pas correcte .
elle effectue une somme alors que nous devrions avoir un comptage
je propose 
$query1 = "select DATE(dateB), **count**(c0) FROM( 
					select date(dateB) as dateb,c0 from data where dateB > DATE_SUB(NOW(), INTERVAL 30 DAY) AND c0 = '5' 
					GROUP by DATE(dateB),HOUR(dateB) )
					as tmp GROUP BY DATE(dateB)";

**Comment by Jahislove** [comment]
merci du tuyau , je prends en compte la correction .
en fait les 2 requetes donnent exactement le même résultat mais c'est vrai que la tienne est plus propre.
par contre j'ai du corriger 
 select date(dateB) as dateb,c0
en 
select dateB as dateb,c0
sinon ça génère une erreur

merci
