### ISSUE TITLE
Information in English or Norwegian?

### ISSUE THREAD

**Issue by petterreinholdtsen** [Jahislove/Hargassner#10]
Hi.  Is there any hope for some information about this project in English or Norwegian?

**Comment by Jahislove** [comment]
hello 
i have updated home page and installation wiki with english translation
hope that will help 
very few comment in code are in english, i'll translate them in a further version

**Comment by petterreinholdtsen** [comment]
[Jahislove]
> hello 
> i have updated home page and installation wiki with english translation
> hope that will help

Thank you.  Where is the home page?  I am only aware of <URL:
https://github.com/Jahislove/Hargassner/ > and its README so far, and it
is still in a language I do not understand.  Perhaps the README should
be extended with the URL to the home page and the git repository, making
it easier for those with only a tarball of the source to locate the
upstream location.

> very few comment in code are in english, i'll translate them in a
> further version

I look forward to it.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by Jahislove** [comment]
home page is in wiki :
https://github.com/Jahislove/Hargassner/wiki

you're right about README , i'll update it

**Comment by Jahislove** [comment]
README is updated

**Comment by petterreinholdtsen** [comment]
[Jahislove]
> README is updated

Thank you very much.  I'll try to get it working with the boiler, now
that I have a slighly better idea how to do it. :)

-- 
Vennlig hilsen
Petter Reinholdtsen
