### ISSUE TITLE
Make web pages translatable?

### ISSUE THREAD

**Issue by petterreinholdtsen** [Jahislove/Hargassner#11]
The current PHP web interface is in French, which is a language I do not understand.  What about adding gettext support and allow the pages to be translated into several languages?

**Comment by Jahislove** [comment]
work in progress

**Comment by NittyGritty74141** [comment]
Bonjour, I can help translate to German and English (if needed)

**Comment by petterreinholdtsen** [comment]
[Nitty Gritty]
> Bonjour, I can help translate to German and English (if needed)

Good to hear more people interested in this.

I've since dropped this php service and moved to a MQTT gateway instead,
reading data from the boiler and broadcasting it via my MQTT broker.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by NittyGritty74141** [comment]
Thanks Petter for your reply. I am using Node Red / InfluxDB / Grafan for all cases, but I was not able to get values from the Hargassner via MQTT. If possible, you can drop me an Info how to get values via MQTT. In general,even this piece of osftware is in french, it is indeed an alternative to the Hargassner Internet gateway and their cloud / web Application - which is just a pale copy of this software.
