### ISSUE TITLE
Support for ECO-HK150 with v16.0b1 firmware V1.0be?

### ISSUE THREAD

**Issue by petterreinholdtsen** [Jahislove/Hargassner#12]
I'm trying to vizualise the information from a Hargassner ECO-HK150 with v16.0b1 firmware V1.0be, and fail to find any of those version numbers in stockBDD.php.  I found the version numbers using the front panel. I suspect the default version number value (14k) is not correct, as some of the shown numbers (like the temperature of the water tank) are way off.  It is currentliy shown as 3 degrees, while it should be closer to 50-60 degrees.  Another example is ambient temperature, which is shown as 1575 degrees right now.  I tried using the latest number (14m) too, but still incorrect numbers displayed on the web page.

Here are some example output lines from telnetting into the boiler:

```
pm 5 7.9 7.1 69.7 84.0 113.1 44 44 84 81 89 83 -1 58 58 1549 792 3 0 3 60.0 -20.0 57.3 54.4 51.0 57.3 70.5 68.0 0 31 -20.0 0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 20.0 20.0 20.0 20.0 20.0 20.0 20.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0 0 0 0 0 0 0 0 1 6 0 0 0 0 0 0 0 0 0 0 0 0 3 80 0 0 2 17 140 0.0 0.0 0.0 0.0 429.1 65 81 14.5 100.0 0 4490.7 0 0 0 0 0 0 0 0 0 0 0 0 140 20.0 20.0 20.0 20.0 20.0 20.0 20.0 2912 4359.0 2.1 269441.6 1.7 0 0.0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 29489.5 9337.6 299.6 7437.5 2142.7 0.0 0.0 0.0 0.0 0 3194 0 9337.6 0.0 0.0 0 0 26 31 0 0 0 0 0 0 0 0.0 0 0 0.0 0.0 0.0 16.0 100.0 57 0 0 0 0 0 0 0 0 -20.0 -20.0 0003 0001 7800 0000 0800 0008 0000 0000 
pm 5 7.8 7.1 69.7 84.0 113.3 44 45 83 81 89 83 -1 58 58 119 0 0 0 3 60.0 -20.0 57.3 54.7 51.0 57.3 70.5 68.0 0 31 -20.0 0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 20.0 20.0 20.0 20.0 20.0 20.0 20.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0 0 0 0 0 0 0 0 1 6 0 0 0 0 0 0 0 0 0 0 0 0 3 80 0 0 2 17 140 0.0 0.0 0.0 0.0 430.1 65 81 14.6 100.0 0 4490.7 0 0 0 0 0 0 0 0 0 0 0 0 140 20.0 20.0 20.0 20.0 20.0 20.0 20.0 2912 4359.0 2.1 269441.6 1.7 0 0.0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 29489.5 9337.6 299.6 7437.5 2142.7 0.0 0.0 0.0 0.0 0 3194 0 9337.6 0.0 0.0 0 0 27 31 0 0 0 0 0 0 0 0.0 0 0 0.0 0.0 0.0 16.0 100.0 57 0 0 0 0 0 0 0 0 -20.0 -20.0 0003 0001 7800 0000 0800 0008 0000 0000 
pm 5 7.8 7.1 69.7 84.0 113.3 44 45 83 81 89 84 -1 58 58 3 0 0 0 0 60.0 -20.0 57.3 54.4 51.0 57.3 70.8 68.0 0 31 -20.0 0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 20.0 20.0 20.0 20.0 20.0 20.0 20.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0 0 0 0 0 0 0 0 1 6 0 0 0 0 0 0 0 0 0 0 0 0 3 80 0 0 2 17 140 0.0 0.0 0.0 0.0 431.5 65 81 14.7 100.0 0 4490.7 0 0 0 0 0 0 0 0 0 0 0 0 140 20.0 20.0 20.0 20.0 20.0 20.0 20.0 2912 4359.0 2.1 269441.6 1.7 0 0.0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 29489.5 9337.6 299.6 7437.5 2142.7 0.0 0.0 0.0 0.0 0 3194 0 9337.6 0.0 0.0 0 0 28 31 0 0 0 0 0 0 0 0.0 0 0 0.0 0.0 0.0 16.0 100.0 57 0 0 0 0 0 0 0 0 -20.0 -20.0 0003 0041 7800 0000 0800 0008 0000 0000
```

**Comment by petterreinholdtsen** [comment]
Here are a few more status lines, this time while there is a error with the stoker skrew.

```
pm 1 21.0 7.0 54.2 0.0 50.4 0 0 0 0 0 0 -1 8 3 0 0 0 0 0 60.0 -20.0 55.5 51.0 48.5 55.5 51.0 58.0 0 28 -20.0 0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 20.0 20.0 20.0 20.0 20.0 20.0 20.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0 0 0 0 0 0 0 0 1 6 0 0 0 0 0 0 0 0 0 0 0 0 3 80 0 0 1 15 140 0.0 0.0 0.0 0.0 58.1 65 186 -9.1 100.0 0 4492.1 0 0 0 0 0 0 0 0 0 0 0 0 140 20.0 20.0 20.0 20.0 20.0 20.0 20.0 2912 4360.6 2.1 269524.4 0.0 0 0.0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 29500.8 9339.9 299.6 7439.9 2143.3 0.0 0.0 0.0 0.0 0 3195 0 9339.9 0.0 0.0 0 0 0 0 0 0 0 0 0 0 0 0.0 0 0 0.0 0.0 0.0 21.0 100.0 53 0 0 0 0 0 0 0 0 -20.0 -20.0 2003 1001 7800 0000 0000 0000 0000 0000 
pm 1 21.0 7.0 54.2 0.0 50.2 0 0 0 0 0 0 -1 8 3 0 0 0 0 0 60.0 -20.0 55.5 51.0 48.5 55.5 51.0 58.0 0 28 -20.0 0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 20.0 20.0 20.0 20.0 20.0 20.0 20.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0 0 0 0 0 0 0 0 1 6 0 0 0 0 0 0 0 0 0 0 0 0 3 80 0 0 1 15 140 0.0 0.0 0.0 0.0 58.1 65 186 -9.1 100.0 0 4492.1 0 0 0 0 0 0 0 0 0 0 0 0 140 20.0 20.0 20.0 20.0 20.0 20.0 20.0 2912 4360.6 2.1 269524.4 0.0 0 0.0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 29500.8 9339.9 299.6 7439.9 2143.3 0.0 0.0 0.0 0.0 0 3195 0 9339.9 0.0 0.0 0 0 0 0 0 0 0 0 0 0 0 0.0 0 0 0.0 0.0 0.0 21.0 100.0 53 0 0 0 0 0 0 0 0 -20.0 -20.0 2003 1001 7800 0000 0000 0000 0000 0000 
pm 1 21.0 7.0 54.2 0.0 50.1 0 0 0 0 0 0 -1 8 3 0 0 0 0 0 60.0 -20.0 55.5 51.0 48.5 55.5 51.0 58.0 0 28 -20.0 0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 -20.0 -20.0 0 0 20.0 20.0 -20.0 0 20.0 20.0 20.0 20.0 20.0 20.0 20.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0 0 0 0 0 0 0 0 1 6 0 0 0 0 0 0 0 0 0 0 0 0 3 80 0 0 1 15 140 0.0 0.0 0.0 0.0 58.1 65 186 -9.1 100.0 0 4492.1 0 0 0 0 0 0 0 0 0 0 0 0 140 20.0 20.0 20.0 20.0 20.0 20.0 20.0 2912 4360.6 2.1 269524.4 0.0 0 0.0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 29500.8 9339.9 299.6 7439.9 2143.3 0.0 0.0 0.0 0.0 0 3195 0 9339.9 0.0 0.0 0 0 0 0 0 0 0 0 0 0 0 0.0 0 0 0.0 0.0 0.0 21.0 100.0 53 0 0 0 0 0 0 0 0 -20.0 -20.0 2003 1001 7800 0000 0000 0000 0000 0000
```

Is there a way to extract the error from the boiler?  I notice the HTTP port (80) is listening, but have no idea which URLs are valid.  The initial try with / as the 'page' just gave

```
<head><title>HIS WEB Server</title></head><body><h2>HTTP 1.0 404 Error. File Not Found</h2>The requested URL was not found on this server.</body>
```

**Comment by Jahislove** [comment]
v14 firmware are for pellet boiler only , parameter in v16 (for wood chip) are not the same
in each firmware (most of time), the order of parameters in the telnet result is not the same.
you need to identify manually the change by experimenting

how far i know, web server is not usable, it is used by the Hargassner server to give order to the boiler via the gateway

the error code is in one of the telnet parameter , but i don't know which one  in v16

**Comment by petterreinholdtsen** [comment]
[Jahislove]
> v14 firmware are for pellet boiler only , parameter in v16 (for wood
> chip) are not the same in each firmware (most of time), the order of
> parameters in the telnet result is not the same.  you need to identify
> manually the change by experimenting

OK.  I can figure out at least some of the values by comparing the
output to the screen on the boiler.  But how do I know what the various
c# values are in stockBDD.php are?  Btw, is json_telnet.php or
stockBDD.php the correct place to add support for a new version/model?
The variable names in json_telnet.php is slightly more expressive than
the ones in stockBDD.php, but not really readable for me. :/

> how far i know, web server is not usable, it is used by the Hargassner
> server to give order to the boiler via the gateway

aha.

> the error code is in one of the telnet parameter , but i don't know
> which one  in v16

Me neither.  Is there a list of known error codes?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by Jahislove** [comment]
json_telnet is the place to reorder parameter for home page in live , i have updated it with english comment
stockBDD is the one to reorder before storing  in database


C# values are detailed in conf/BDD_description_chanel.txt but sadly in french.
this file is the original parameter order , from the first firmware(where  SQL order is the same that telnet order) , i'll try to tranlate it next week

with newer firmware, telnet order change , this is why, we need to re-order before writing in database

beware if you change my code , there is a semi auto update feature , and when i push a new version , if you click yes , that will replace your work with my new version

to be safe , if you find the correct order for your boiler , i'll suggest that you send me your parameters , so i can add it to my site, that way it will work with all new version

**Comment by petterreinholdtsen** [comment]
[Jahislove]
> json_telnet is the place to reorder parameter for home page in live ,
> i have updated it with english comment
> stockBDD is the one to reorder before storing  in database

Thank you.  I'll get started.  Will take a while until I get through
them all. :)

> C# values are detailed in conf/BDD_description_chanel.txt but sadly in french.
> this file is the original parameter order , from the first
> firmware(where  SQL order is the same that telnet order) , i'll try to
> tranlate it next week

Great.

> with newer firmware, telnet order change , this is why, we need to
> beware if you change my code , there is a semi auto update feature ,
> and when i push a new version , if you click yes , that will replace
> your work with my new version

Will keep that in mind.  I'll send a pull request when I have something
useful.

I've been able to identify some values I have been recording from the
front panel so far, from one of the screens showing accumulated values.
The english field names are translated from norwegian, not sure I got
them right.  Here is the script I can use instead of reading from screen
going forward:

#!/bin/sh
# Output stats with the values also available on the front panel of the wood
# burner.  The values returned are
# timestamp epoctime "hours control unit" "hours heating" "hours
# igniting" "hours exhaust fan" "hours running stoker skrew" "hours
# running transport skrew" "clean count small" "clean count large"

retval=0

line="$(true | nc -W 3 192.168.0.1 23 | head -1)"
if [ -z "$line" ] ; then
    msg="Failed to fetch status from boiler" 
    echo "$msg" | logger -t hargassner-eco-hk150
    echo "$msg"
    exit 1
fi

echo $(date --iso=s) $(date +%s) $(echo "$line" |awk '{print $158, $159, $160, $161, $114, $162, 0, $168}') | sed 's/+01:00/CET/' | tr " " "\t"


-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Here is my first draft on guessing the values returned, based on looking
at the screen and comparing it to the values returned from telnet.  I am
not sure if the field descriptions make sense.  Some of them are
translated directly from the Norwegian display on the screen.

Btw, do you know any HTTP commands and what they can do?

Here are my notes so far:

Telnet protocol for ECO-HK150 with v16.0b1 firmware V1.0be
==========================================================

These are the values returned by a Hargassner ECO-HK150 with software
version v16.0b1 firmware version V1.0be when connecting to its IP
address on port 23.

This list consist of Field number, example-value and explanation /
description:

000 pm
001 1 - state, 4, 5 or 7 when boiler is burning, 1 when idle
002 2.3  - O2 level % (sett)
003 7.0 - O2 level % (er)
004 34.2 - boiler temperature / water (sett)
005 0.0 - boiler temperature / water (er)
006 31.3 - exhaust temperature C
007 0 - exhaust suck % (sett )
008 0 - exhaust suck % (er)
009 0 - primary air % (er)
010 0 - primary air % (sett)
011 0 - % burning
012 0 - feed amount % (er)
013 -0
014 3
015 3 - glob bed degrees (er)
016 0 - milliampere stoker screw
017 0 - milliampere transport screw
018 0
019 0
020 0
021 60.0
022 -20.0
023 13.4 - ambient temperature?
024 12.9 - ambient temperature?
025 12.6 - ambient temperature?
026 13.4 - ambient temperature?
027 29.8 - return temperature C (re)
028 58.0 - return temperature C (sett)
029 0
030 19
031 -20.0
032 0
033 20.0
034 -20.0
035 0
036 -20.0
037 -20.0
038 0
039 0
040 20.0
041 20.0
042 -20.0
043 0
044 -20.0
045 -20.0
046 0
047 0
048 20.0
049 20.0
050 -20.0
051 0
052 -20.0
053 -20.0
054 0
055 0
056 20.0
057 20.0
058 -20.0
059 0
060 20.0
061 20.0
062 20.0
063 20.0
064 20.0
065 20.0
066 20.0
067 0.0
068 0.0
069 0.0
070 0.0
071 0.0
072 0.0
073 0.0
074 0
075 0
076 0
077 0
078 0
079 0
080 0
081 0
082 1
083 6
084 0
085 0
086 0
087 0
088 0
089 0
090 0
091 0
092 0
093 0
094 0
095 0
096 3
097 80
098 0
099 0
100 0
101 13
102 140
103 0.0
104 0.0
105 0.0
106 0.0
107 35.8 - temperature fire chamber C
108 65 - glow bed degrees (sett)
109 186
110 49.9 - fire chamber temperature
111 100.0
112 0
113 4492.1 - hours stoker screw
114 0
115 0
116 0
117 0
118 0
119 0
120 0
121 0
122 0
123 0
124 0
125 0
126 140
127 20.0
128 20.0
129 20.0
130 20.0
131 20.0
132 20.0
133 20.0
134 2912
135 4360.6
136 2.1
137 269524.4
138 0.0
138 0
139 0.0
140 0
141 0
142 0
143 0
144 0
145 0
146 0
147 0
148 1
149 1
150 1
151 1
152 1
153 1
154 1
155 0
156 29514.3 - hours on control unit
157 9339.9 - hours heating
158 299.6 - hours igniting
159 7439.9 - hours running fan
160 2143.3 - hours transport screw
161 0.0
162 0.0
163 0.0
163 0.0
165 0
166 3195 - number of cleaning "large"
167 0
168 9339.9
169 0.0
170 0.0
171 0
172 0
173 0 - tertiary air % (sett)
174 0 - tertiary air % (er)
175 0
176 0
177 0
178 0
179 0
180 0
181 0
182 0.0
183 0
184 0
185 0.0
186 0.0
187 0.0
188 21.0
189 100.0
190 0 - heat fill level % water tank
191 0
192 0
193 0
194 0
195 0
196 0
197 0
198 0
199 -20.0
200 -20.0
201 2003 - status, 0003 ok, 2003 error
202 1000
203 7800
204 0000
205 0000
206 0000
207 0000
208 0000

-- 
Happy hacking
Petter Reinholdtsen
