### ISSUE TITLE
Include version number in JSON output from json_telnet.php?

### ISSUE THREAD

**Issue by petterreinholdtsen** [Jahislove/Hargassner#13]
What about including the software version number in the JSON output from json_telnet.php, to both allow clients to know what to expect, and to allow the web interface to show the version number used when parsing the telnet output?  It could also include a version number of this program package itself.

If the attribute names were in english and every field fetched from telnet was available as JSON, this would be my preferred way to fetch information from the boiler.  Alas that is not yet true. :)

**Comment by Jahislove** [comment]
not sure if it could help , there is no way to know which firmware version is in the telnet answer.
the version number is put manually in config.inc.php , so you already know it

**Comment by petterreinholdtsen** [comment]
[Jahislove]
> not sure if it could help , there is no way to know which firmware
> version is in the telnet answer.
> the version number is put manually in config.inc.php , so you already
> know it

The requestor of the JSON structure might now have access to
config.inc.php, nor be told when the config change

-- 
Happy hacking
Petter Reinholdtsen
