### ISSUE TITLE
firmware V14.0n3

### ISSUE THREAD

**Issue by phill22** [Jahislove/Hargassner#18]
hello,

this week we gat an firmware update from the hargassner service man. our new firmware is V14.0n3 and now all datas are confusing. is ther an workaround? an new firmware file?

best regards

-------

bonjour,

cette semaine, nous avons reçu une mise à jour du firmware de l'homme de service hargassner. notre nouveau firmware est V14.0n3 et maintenant toutes les données sont déroutantes. existe-t-il une solution de contournement ? un nouveau fichier de firmware ?

cordialement

**Comment by Jahislove** [comment]
quelle était votre version précedente ?

**Comment by phill22** [comment]
Je ne sais pas exactement quelle version du firmware était auparavant sur la chaudière. mais avec le paramètre "14m" dans config.php cela a fonctionné.

Au fait, merci beaucoup pour ce super script / projet ! et merci beaucoup pour votre travail.

**Comment by phill22** [comment]
https://ibb.co/7jMsY53
https://ibb.co/ft5TWyw
https://ibb.co/WVRJxzF

**Comment by Jahislove** [comment]
il faudrait me fournir un fichier DAQ contenant les données . on peut le récupérer dans insérant une carte SD et en activant :
réglage / configuration / enregistrement en continu sur carte SD

il suffit de laisser tourner 2-3 minutes , ça suffira

au passage le tableau dans la page Données est plus joli que ça :) il faudrait faire SHIFT-F5 pour recharger la page sans le cache

**Comment by phill22** [comment]
Je peux le faire le week-end prochain. le nano-pk est chez mes parents (à plus de 300 km)

**Comment by phill22** [comment]
Voici à quoi cela ressemble lorsque j'accède directement à la page sans proxy inverse :

https://ibb.co/tBZZ8vQ

**Comment by phill22** [comment]
Je peux poster le "DAQ" dans quelques jours

**Comment by phill22** [comment]
https://kochinger.net/sdcard.zip

**Comment by Jahislove** [comment]
je viens de mettre a dispo la version 3.7 qui embarque le firmware 14n
pense a modifier ta version dans conf/config.inc.php en mettant 14n
il y a beaucoup de changement et de parametres en moins. previens moi si tu vois des anomalies

**Comment by MaKiNeRoS** [comment]
Bonjour @Jahislove 
Je me permet de répondre directement sur ce sujet car je dispose depuis quelques mois d'un chaudière Hargassner NanoPK 9 en version 14.0n3.
Tout d’abord, je voulais te remercier de nous permettre d'utiliser ton travail.
 
Du coup, j'ai installé WAMP sur un PC ainsi que la dernière version (3.7) de ton projet.
J'ai constaté que la page d’accueil n'indiquait pas les bonne valeur, en fouillant un peu, cela provient de la page "json.telnet.php" dont il manque le firmware 14n. Comment puis je partager les modifications ?
Autre point, mon fichier DAQ ne colle pas a celui de phill22. J'ai ANALOG que jusqu’à ID103 puis DIGITAL de ID0 a ID7

Cordialement

**Comment by Jahislove** [comment]
pour ton DAQ qui ne colle pas c'est bizarre , normalement ils devraient etre identique . mais de toute facon les id 104 à 107 ne sont pas utilisés.

pour le probleme de json_telnet.php , bin c'est simple , j'ai oublié de le mettre a jour.
je te fait ça le plus rapidement possible

**Comment by MaKiNeRoS** [comment]
Pour info, voici mon DAQ
[ST_LIST.CSV](https://github.com/Jahislove/Hargassner/files/11425245/ST_LIST.CSV)
[DAQ00000.DAQ.txt](https://github.com/Jahislove/Hargassner/files/11425251/DAQ00000.DAQ.txt)

Dans "firmware.inc.php", 103 doit aller dans c175.
Et si je me base sur "BDD_description_chanel.php", j'ai plusieurs paramètres dont le NAME ne correspond pas 


<html>
<head>
</head>
<body>


ID | NAME | UNIT | DOP | a vérif
-- | -- | -- | -- | --
15 | Puffer_soll oben | °C | 0 | c96
16 | Puffer_soll unten | °C | 0 | c106
22 | min.Leist.TRG | % |   | c48
23 | max.Leist.TRG | % |   | c49
24 | max.Leist.Fuell | % |   | c50
25 | max.Leist.TPO | % |   | c51
29 | Programm |   | 0 | c121
30 | Stĥrungs Nr |   | 0 | c97
37 | LZ ES seit Ent. | Min | 0 | c111
42 | Heiz P Lambda | W | 2 | c154
43 | Heiz U Lambda | V | 2 | c130
44 | Heiz I Lambda | mA | 0 | c136
46 | U Netzteil | mV | 0 | c79
47 | T Spĵlung | °C |   | c73
50 | TVG | °C |   | c76
51 | TVG2 | °C |   | c119
74 | TVL_B | °C |   | c120
75 | TVLs_B | °C | 0 | c41
76 | TRA_B | °C |   | c187
77 | TRs_B | °C |   | c42
78 | HKZustand_B |   | 0 | c186
79 | FRB Zustand |   | 0 | c188
85 | TBB | °C |   | c80
86 | TBs_B | °C | 0 | c118
87 | HKR Anf | °C |   | c145


</body>

</html>

**Comment by MaKiNeRoS** [comment]
Le nouveau json_telnet.php semble fonctionner correctement.

Petite question, est il possible de rajouter d'autres courbes dans les courbes en temps réel ?

![image](https://github.com/Jahislove/Hargassner/assets/132904974/83be1a8e-a63c-4879-872c-9a570fbfe10a)

**Comment by MaKiNeRoS** [comment]
Information complémentaire, dans mon cas, le telnet 104 semble aussi être alphanumérique (mais il fait partie des info DIGITAL)

![image](https://github.com/Jahislove/Hargassner/assets/132904974/5135c0e1-1cf9-4afd-a554-31681d144aa3)

**Comment by Jahislove** [comment]
oui je peux ajouter des courbes,  dit moi ce que tu veux

**Comment by MaKiNeRoS** [comment]
J'aurais voulu avoir la température intérieure et la température du ballon si c'était possible.
Ne serait il pas intéressant d'avoir un listing de l'ensemble des ressources possible et pouvoir cocher celle a tracer depuis page_reglages.php

Si un petit problème avec la courbe allumeur électrique, elle reste sur "loading". 
Et quand je lance directement json_allumeur.php, j'ai le message d'erreur suivant : 

`<br />
<b>Warning</b>:  mysqli_fetch_row() expects parameter 1 to be mysqli_result, boolean given in <b>C:\Serveur\www\Hargassner\json_allumeur.php</b> on line <b>26</b><br />
null`

Je constate aussi la même erreur en bas de page_3_conso.php

`Warning: mysqli_fetch_row() expects parameter 1 to be mysqli_result, boolean given in C:\Serveur\www\Hargassner\page_3_conso.php on line 85`

**Comment by Jahislove** [comment]
pour moi tu n'arrive pas a acceder a la BDD , essaye de tester la connexion avec le fichier testBDD.php ( faut modifier les parametres a l'interieur)

**Comment by MaKiNeRoS** [comment]
Bonsoir, 

Désolé pour le délais de réponse. J'avais mis de coté le temps de basculer le tout sur un NAS Synology.
J'ai installé un système propre. 

Les courbes fonctionnent correctement mais dès que la chaudière démarre, plus d'enregistrement.
Il y a une correction a apporter dans "firmware.inc.php"
`Incorrect decimal value: 'A' for column `hargassner`.`data`.`c81` at row 1 `

**Comment by Jahislove** [comment]
j'ai uploadé un correctif , recupere et remplace juste le fichier firmware.inc.php
