### ISSUE TITLE
php 7 ne supporte plus l'extension mysql_*

### ISSUE THREAD

**Issue by daeavelwyn** [Jahislove/Hargassner#2]
Salut salut,

Merci beaucoup pour l'énorme boulot que tu as fait, je viens de mettre tout ça en route chez moi. J'ai cependant un gros soucis, c'est que j'utilise un TerraMaster F2-220 avec leur O.S. TOS 4.1.3 et malheureusement, la version de php fournit est la 7.1.13 or, depuis la version 7 de php, certaines fonctions de connexion à la bdd ne sont plus présente (https://www.php.net/manual/fr/function.mysql-connect.php) du coup, j'ai tenté de changer un peu ça mais ça me fout un bordel sans nom car je n'ai pas la vision globale du code qui me permettrait de faire un truc qui fonctionne.

J'ai vu qu'il y a un fichier StockBDD-php7-test.php, comment utiliser ce script ?

**Comment by daeavelwyn** [comment]
bon j'avance dans la compréhension de ton code mais j'ai un soucis :
```
 php -c /mnt/md0/appdata/hargassner/conf/php.ini -f /mnt/md0/appdata/hargassner/stockBDD-php7-test.php
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/mysqli.so' - /usr/lib/php/modules/mysqli.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/mysql.so' - /usr/lib/php/modules/mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
Error: INSERT INTO data  VALUES (null, '2020-10-02 19:36:47','9','20.3','12.5','77.0','72','83.4','24','25','0','0','3','0','0','0','0','11','12','120','-20','120','-20','120','125','120','58','27','107.8','84.7','67','25','0','0','55','194','0','21','9.00','14.34','628','-5','0','0','100','100','0','0','3068','54','1','0','-20','0','20','20','0','1','32.4','33','19.2','20','1','1','140','0','20','20','0','1','-20','0','20','20','0','1','-20','0','20','20','0','1','-20','0','20','20','0','1','-20','0','20','20','0','1','-20','0','0','52.9','0','0','-20','0','0','-20','0','0','0','0','0','33','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-20','-20','-20','-20','-20','-20','0','-20','0','0','-20','0','20','20','0','20','1','0089','0001','0000','0000','0000','0060','0000','0000','
')<br>Column count doesn't match value count at row 1
```

Les warning PHP sur mysql et mysqli ne sont pas à prendre en compte je pense car j'ai phpmyadmin qui tourne niquel donc c'est que ces extensions php fonctionnent non ?

**Comment by Jahislove** [comment]
bonjour,

la réponse est non :) 
l'utilisation de PHP en ligne de commande n'utilise pas le même fichier .ini  que l'utilisation par un navigateur.
et tout le monde fait la meme erreur en pensant que si ça marche par le navigateur  ça va marcher pareil en ligne de commande
c'est pour ça que j'utilise le fichier conf/php.ini ( utilisé uniquement par stockBDD en ligne de commande)

mais il faut personnaliser ce fichier avec ton propre chemin, la solution est dans le fichier php.ini :)  
 **personnaliser cette ligne en lancant la page phpinfo.php dans le navigateur et en cherchant extension_dir
extension_dir = "/usr/local/lib/php56/modules"**

le fichier StockBDD-php7-test.php est un test que j'avais commencé a un moment , il permet d'écrire les valeurs venant de la chaudiere en BDD.

mysqli.so est utilisé par PHP7 et mysql.so par php5.6

sinon je t'informe que Hargassner met a disposition depuis 2 semaines un site web https://web.hargassner.at/login
qui est pas mal fait a part qu'il ne fait des mesures que toutes les 15mn au lieu de 1 mn pour moi
si t'es patient , il faudra bien  que je me mette au boulot pour migrer en php7 mais c'est pas pour tout de suite , je verrais cet hiver

**Comment by daeavelwyn** [comment]
Ok,
Alors le site Hargassner a été ma première option, mais après un échange avec le SAV, il faut une passerelle qu'ils vendent pour pouvoir s'en servir. Voici la réponse du SAV : 

`Effectivement avec votre installation HARGASSNER vous pouvez connecter votre chaudière à l’application HARGASSNER APP 2.0.

Pour que cela possible votre installation HARGASSNER doit être équipée d’une passerelle internet (a commander chez nous).

Je viens d’avoir votre installateur chauffagiste au téléphone qui me confirme que votre installation n’est pas équipée de cette passerelle internet.

Donc impossible pour le moment de connecter votre chaudière à l’application sans cette passerelle internet.

Pour toutes informations complémentaires à l’application veuillez prendre connaissance des lien ci-dessous :

 

·         http://downloads.hargassner.at/Export/Hargassner_APP-WEB_Telechargement-et-enregistrement__FRA_2020.pdf

·         http://downloads.hargassner.at/Export/Hargassner_APP-WEB_FRA_2020.pdf

·         http://downloads.hargassner.at/Export/Hargassner_APP-WEB_Soutien_FRA_2020.pdf

 

Si vous souhaitez connecter votre chaudière à l’application merci de vous rapprocher de votre chauffagiste « SARL Kerbaul » pour l’installation de cette passerelle internet.

Le prix de cette passerelle internet est de 140 € HT prix.

 

Merci de votre compréhension.

Bonne réception`

**Comment by Jahislove** [comment]
oui je te confirme tout :)

tu as besoin de mysqli , cette library sert a interagir avec une BDD mysql/mariaDB, et normalement , par defaut elle est bien pré-installé sur le disque mais elle n'est pas configuré dans php ( et phpmyadmin n'en a pas besoin , donc il ne faut pas le prendre comme reference) 

pour que mysqli soit pris en compte et apparaisse dans phpinfo()
il faut que le serveur php soit démarré avec l'extension mysqli
si tu as une interface graphique pour configurer php il y a de forte chance qu'il y ai juste une case a cocher , certainement dans les parametres avancés

**Comment by daeavelwyn** [comment]
Ok, bon j'ai bien avancé, maintenant le code est complètement réécrit pour php7 et fonctionne concernant cet aspect des choses. Par  contre, j'ai une classic15 et pas une nanoPK et donc les correspondances de c* sont vraiment complexe à gérer. ça m'aiderait beaucoup si tu pouvais me dire comment tu as obtenus le fichier `channel-nanoPK-v14.0k.txt` là j'y vais un peu à l'aveugle et y a des valeurs dont je ne suis pas sûr de la correcpondance....

**Comment by Jahislove** [comment]
l'important c'est la version du firmware , car il n' y a pas de difference entre nano et classic
si ton firmware est relativement recent (>14e) il est deja pris en compte par mon script stockBDD.php (le stock..testphp7 est incomplet il faut t'inspirer du stockBDD)
le fichier chanel s'obtient directement sur la chaudiere avec une carte SD , il s'agit d'un fichier de données .DAQ  quelconque . le debut du fichier contient les chanel , le reste est illisible

dans le fichier BDD_description , tu as la correspondance chanel et colonne BDD 
important : la correction eventuelle de  l'ordre des chanel se fait avant d'ecrire en BDD . car ensuite la lecture est identique quelque soit la version/chaudiere

**Comment by daeavelwyn** [comment]
Alors alors, j'avance un peu. Merci pour les précisions !
Donc pour la correspondance nano / classic, en fait, c'est pas du tout les mêmes. J'a récupéré les channel via une carte SDet j'ai donc le fichier DAQ comme tu l'as indiqué. Cool ! (et encore merci pour l'info !). 

Par contre, il y a beaucoup de différence entre les deux. Je te joins le tableau de correspondance que j'ai dressé. J'ai remplacé le num c1 / c10 / c100 par un indice unique à 3 chiffre c***, ^plus facile pour le tri.

Que préconises-tu pour créer la compatibilité des deux chaudières ? J'avais pensée à une variable dans config.inc.php qui indique le type de chaudiere (nano ou classic), ensuite, créer un case dans le stockBDD.php pour créer la compatibilité et indexer la classic 15 sur la nanoPK vu que l'ensemble du code est pensé pour la nanoPK. Qu'en penses-tu ?

[hargassnerr_correspondance_nanoPK_classic15.xlsx](https://github.com/Jahislove/Hargassner/files/5324151/hargassnerr_correspondance_nanoPK_classic15.xlsx)

**Comment by Jahislove** [comment]
je suis quand meme surpris de ce que tu dit , pour moi seule la version du firmware compte , tu es en quelle version ?

sinon le mieux c'est effectivement d'utiliser ce qui existe deja dans le fichier config et stockBDD (un case) et d'ajouter une autre variable specifique aux classic
par exemple 14kClassic , pour un firmware 14k sur une classic .


le principe c'est que les colonnes de la BDD sont fixes , elles ne bougent jamais , par exemple la c134 c'est la puissance et ça restera toujours la puissance .
dans le cas des chaudiere ou l'ordre est different,  c'est  au moment du stockage qu'on change  l'ordre des chanel. si sur ta chaudiere la puissance est le chanel 55 , alors dans stockBDD on dit de stocker le parametre telnet 55 dans la colonne 134 de la BDD . comme ça il n'y a jamais besoin de toucher au reste du site

**Comment by daeavelwyn** [comment]
ok ok, Alors effectivement, j'ai utilisé le fichier `BDD_description_chanel.txt` pour ma comparaison. Donc, les channels de ce fichier sont les channels originaux de la BDD si je comprends bien ?
Du coup, en prenant le fichier `channel-nanoPK-v14.0k.txt`, je me retrouve bien avec la correspondance dont tu parles et les channels de mon firmware (14.0l, de mai 2020) sont identiques à ceux du fichier `channel-nanoPK-v14.0k.txt` (à part quelques valeurs).
Si j'ai bien suivi, c'est le fichier` json_telnet.php` qui s'occupe de la traduction en tps réel de ces valeurs et assure la compatibilité du site avec les différents firmaware. Par contre, il me semble qu'il n'y a aucune translation de valeur dans stockBDD.php, donc les valeurs stockées dans la BDD sont les valeurs brut extrait de la sortie de telnet ? Ou alors j'ai zappé un truc ?

**Comment by daeavelwyn** [comment]
bon, passage à php7 finit normalement.

**Comment by Jahislove** [comment]
le json_telnet ne fait que lire les parametres de la chaudiere , c'est  bien le stockBDD qui change l'ordre des parametres dans la requete d'insertion en BDD
tu as un firmware plus recent que le mien et depuis quelques temps hargassner semble réduire le nombre de parametres accessible en telnet. du coup je n'ai pas de solution

**Comment by daeavelwyn** [comment]
Je te joins ce que la page variables affiche chez moi, je n'y connais pas grand chose en chaudière, si tu peux m'indiquer si certaines valeurs te semblent ne pas correspondre, ça m'aiderait à corriger le code pour ma chaudière et mon firmware.
ok, bin à mon avis ils vont essayer de propulser un peu plus leur solution de site web, et donc vendre leur passerelle à 140€ et donc effectivement, y a des chances qu'on se retrouve au final avec de moins en moins de possibilité d'accéder aux infos....
Quoi qu'il en soit, merci beaucoup pour le temps que tu me consacres ! :)
![Sans titre](https://user-images.githubusercontent.com/4292225/95208845-ee329980-07e9-11eb-82be-59de819c1aa2.png)

**Comment by daeavelwyn** [comment]
ok, fait moi signe quand tu l'as uploadé ;)

**Comment by Jahislove** [comment]
Salut , j'ai uploadé une nouvelle version en php 7 
j'ai également ajouté la prise en charge du  firmware 14l ( en supposant qu'il soit identique au precedent)
tout le site est réécrit pour php7 .le stockBDD aussi 
pense a sauvegarder ton site avant de le remplacer par celui ci (mais conserve ton config.inc.php et ton php.ini)
si tout fonctionne correctement , je publierai le changement de version et a ce moment la ,
comme j'utilise un systeme de mise a jour automatique , ton site devrais afficher un bouton de mise a jour.
pour toi , ca ne fera que remplacer ta version par la meme , mais c'est plutot pour les autres utlisateurs
