### ISSUE TITLE
Firmware V14.0HAR.o

### ISSUE THREAD

**Issue by VinceDCS** [Jahislove/Hargassner#20]
Bonjour,

Ayant subit une mise a jour du firmware, la supervision est toute casée :(

En pj le DAQ 
[DAQ.zip](https://github.com/Jahislove/Hargassner/files/12506348/DAQ.zip)

Hésite pas si besoin d'autres informations 
Bonne fin de journée

**Comment by Jahislove** [comment]
Bonjour
je viens d'uploader la 3.8 qui ajoute le firmware V14.0HAR.o
pense a le modifier dans ton config.inc.php
tiens moi au courant si tu voit des anomalies
