### ISSUE TITLE
new Software release Nano PK V14.0HAR.p

### ISSUE THREAD

**Issue by NittyGritty74141** [Jahislove/Hargassner#22]
Since July, 18th, there is a new DW release which is not compatible with the current (latest) file channel-nanoPK-v14.0HAR.o2.txt
I found, that at least t41/c99 and t40/c115 have been shifted. Also t53/c6 and t65/c7 have been shifted PLUS one "place"
Unfortunately I have no more information on the modification.

If I run test_telnet-php, I get this string:

pm 1 1.2 7.9 20.7 0 21.2 35 13 26.1 0 0 57.4 120 47.7 74 5 0 0 0 57 0 0 30.1 100 85 85 0 77.2 87 1 0 0 9 2 0 1 0 0 0 0 1182 3211 1790 0.00 0.00 -3 50.5 24059 140.0 105.8 28 -20.0 -20.0 0.0 24.3 22.2 0 -20.0 0 20.0 20.0 0 1 21.1 0 20.0 20.0 0 4 140.0 0 20.0 20.0 0 1 -20.0 0 20.0 20.0 0 1 -20.0 0 58.8 0 0 -20.0 0 0.0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.00 402 0 0 0 1 0 0 0

**Comment by Jahislove** [comment]
can you send me a .DAQ file, you can get one with an SD card and using config menu. if the file is too big, i only need the beginning of the file ( all chanel name)

**Comment by Jahislove** [comment]
are you sure you are using V14.0HAR.o2 ? when you say t41/c99 and t40/c115 it look like you are using a 14.0n or previous , as since V14.0HAR.o it's t41/c115 and t40/c114

**Comment by NittyGritty74141** [comment]
version 3.9 worked well until July 18th, 
![July18th](https://github.com/user-attachments/assets/f8b5743e-508d-4ac4-964f-d359db1a481d)
According to the information of my Hargassner on  the webseite, you can see Software version changed
![NanopkVerison](https://github.com/user-attachments/assets/44387db8-6bc0-40d2-9fec-ee46b41e83e5)
I will get to my house later the day and will pick the requested file via SD card
Unfortunately I am not that deep involved in all parameters youmentioned before, I'm just "user" of your program - but try to get it up & running again :-)

**Comment by NittyGritty74141** [comment]
so far, the swoftware worked with this parameter in config.inc.php
$firmware= "14n" ;
Shall I set this to another (which?) value?

**Comment by Jahislove** [comment]
try 
$firmware= "V14.0HAR.o2" ;

**Comment by NittyGritty74141** [comment]
Thanks for this hint - I changed the parameter - most seems OK _ even the heating is turned off, the "pompe radiateur" is "rotating" - which is i.m.o. no correct. Also ECS show 0°C (see screenshot)
![Clipboard03](https://github.com/user-attachments/assets/ee58a89f-dfa9-4a50-8290-83b4909086af)
I got the .DAQ file - shall I append it here?

**Comment by NittyGritty74141** [comment]
[DAQ00000.zip](https://github.com/user-attachments/files/16446747/DAQ00000.zip)

**Comment by Jahislove** [comment]
thx, i'm working on it , give me some time

**Comment by Jahislove** [comment]
new version 4.0 available , you should install it.
don't forget to modify $firmware= "V14.0HAR.p" ;  in your config.inc.php

please tell me if you see any error

**Comment by NittyGritty74141** [comment]
I installed the two changed files manually and updated config.inc.php as above. Now works perfect again. Thank you very much for your support - and also for this program.
Will you supply other languages in the future? If so, I can offer my help in translating to german / english.

**Comment by Jahislove** [comment]
i can think about that when i get some time :)

**Comment by NittyGritty74141** [comment]
I expected that reply :-) - anyway, thanks again for your brilliant work!

**Comment by Jahislove** [comment]
translation in progress,  ETA next week
