### ISSUE TITLE
consommation de granulés cumulés versus consommation pour la période

### ISSUE THREAD

**Issue by MathieuCGit** [Jahislove/Hargassner#26]
Bonjour,

Tout d'abord merci pour ce petit bijou de code qui rend de fiers services ! Je rencontre un soucis depuis mon passage à la dernière version, j'ai mis du temps à comprendre d'où ça pouvait venir mais je crois avoir compris.

J'utilise la dernière version du site (avec un git clone pour être sûr d'avoir les mises à jour).

J'ai une Hargassner classic 15 installée en 2019 et j'ai fait ma mise à jour avant de relancer la chaudière pour la saison 2023/2024. Au redémarrage, le logiciel me renvoi comme quantitée de granulés consommés, la valeur totale de la consommation de la chaudière depuis sa mise en service (10680Kg) au lieu de la consommation depuis le 31 octobre, date de sa remise en service.

J'imagine qu'il y a une intervention à faire au niveau de la bdd mais vu la taille de la bdd, je ne sais pas trop où chercher, d'où ce ticket :)

Merci par avance de votre aide.

**Comment by MathieuCGit** [comment]
J'ai aussi tenté de jouer avec ce paramètre dans le config.inc.php

`$consoHeure = 38; // = parameter R8a in factory parameter of the boiler`

Mais visiblement ça ne change rien. A quoi correspond ce paramètre ?

**Comment by Jahislove** [comment]
Bonjour
le parametre usine R8a  corresponds a une valeur de reference permettant a la chaudiere de calculer combien de granulés elle consomme .
en gros quand elle dit qu'elle a consommé 1 kg , en réalité elle ne pèse pas les granulés, elle les calcule.
ici sur une Nano9 ça corresponds a 38 tours de vis par heure , en sachant que la Nano9 consomme 2.2 kg/heure.
ça lui permet de faire son petit calcul.
2.2kg/h, je l'ai pas inventé, je le sais car sur les premiers firmware le R8a était justement 2.2 kg/h , mais maintenant ils l'ont remplacé par 38 tr/h.
pour finir si on fait  2.2kg/h x 4600wh/kg =9200 wh , ce qui correspond bien a une Nano  9Kwh

sur une classic 15 ce R8a est forcement different , on pourrait l'estimer a 63 avec une regle de 3 mais la taille de la vis est certainement differente.

tout ça pour dire que $consoHeure reprends juste la valeur de R8a pour afficher la conso en temps reelle sur la page d'acceuil. 
elle ne sert absolument pas pour autre chose

chose intéressante avec le R8a sur la chaudiere c'est qu'il est personnalisable et n'a pas d'influence sur le fonctionnement de la chaudiere , il ne fait que modifier la consommation totale calculé par la chaudiere. du coup on peut l'utiliser pour calibrer la conso si la chaudiere calcul mal. exemple si tu rempli ton silos de 2000kg , quand il est vide , si la chaudiere te dit que tu as consommé 2500kg c'est que c'est mal calibré , on peut le modifier avec une regle de 3

**Comment by MathieuCGit** [comment]
Ah ok, merci des infos ! Quelles autres infos je pourrais te fournir pour résoudre mon soucis ?
Voici une capture d'écran du soucis :  [https://imgur.com/tAr4vnB](https://imgur.com/tAr4vnB)

**Comment by Jahislove** [comment]
je pense que la colonne que tu cherche est dans la table consommation , colonne conso
donc dans ton logiciel de gestion de ta BDD (phpmyadmin ? )tu peux directement afficher la table consommation et tu trouvera ta valeur, il te suffit de l'editer directement.

si tu n'a pas de phpmyadmin , le plus simple est d'installer HeidiSQL sur un PC windows , c'est un logiciel de gestion de BDD

sinon, en ligne de commande :
se connecter mysql , puis lancer l'interface mysql.

 puis la requete pour afficher cette colonne :
`SELECT * FROM hargassner.consommation ; `

**Comment by Jahislove** [comment]
et pour remplacer la valeur (remplace 10 par la conso du jour)
`update  consommation
SET conso = 10
WHERE conso = 10680 ;`

**Comment by MathieuCGit** [comment]
Ah yes !! Totalement merci !

J'utilise adminer (que je trouve plus facile à déployer que phpmyadmin) et du coup la valeur 10860 date de juin, date à laquelle je n'avais pas la chaudière en route donc facile de calculer la conso ! J'ai utilisé cette requête:
```
update  consommation SET conso = 0 WHERE conso = 10680 ;
```
Et tout semble rentré dans l'ordre !

Un grand merci encore à toi !

**Comment by MathieuCGit** [comment]
requête SQL erronée
