### ISSUE TITLE
Erreur SSL de connexion à GitHub

### ISSUE THREAD

**Issue by daeavelwyn** [Jahislove/Hargassner#3]
Je viens de tester la dernière version et j'ai un message d'erreur : 

```
Warning: fopen(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /mnt/md0/appdata/hargassner/header_fin.php on line 7

Warning: fopen(): Failed to enable crypto in /mnt/md0/appdata/hargassner/header_fin.php on line 7

Warning: fopen(https://raw.githubusercontent.com/Jahislove/Hargassner/master/conf/version.php): failed to open stream: operation failed in /mnt/md0/appdata/hargassner/header_fin.php on line 7
impossible de joindre github pour vérifier les mises a jour, si le problème persiste vérifiez que votre serveur php est bien lancé avec les extensions openssl et zip

```
Or php est bien lancé avec les extensions openssl et zip : 

```
php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
php_terra_master
posix
readline
redis
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
SPL
sqlite3
standard
sysvshm
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules
```

**Comment by Jahislove** [comment]
c'est utilisé uniquement pour les mises a jour auto , 
je verifie le soucis

**Comment by Jahislove** [comment]
je n'arrive pas a reproduire le problème , chez moi ça marche .
chez toi on voit bien qu'il n'arrive pas a joindre le github pour verifier les nouvelles versions

et en chargeant la page phpinfo.php , openssl  apparait bien aussi ?

**Comment by daeavelwyn** [comment]
yep, voici l'excerpt en image : 
![opennssl-enabled](https://user-images.githubusercontent.com/4292225/96183852-d8367e80-0f37-11eb-8afb-3987efccf237.png)

**Comment by daeavelwyn** [comment]
Après plusieurs recherches, il semble que ce soit aussi un soucis lié à l'upgrade vers une nouvelle version de PHP, le plus probant que j'ai pu trouver c'est là : [https://stackoverflow.com/questions/32211301/ssl-error-ssl3-get-server-certificatecertificate-verify-failed](url).
Pour l'heure je pense que je vais commenter le code du mécanisme de vérification de nouvelle version.
