### ISSUE TITLE
Hargassner V14.l - étrangetés

### ISSUE THREAD

**Issue by daeavelwyn** [Jahislove/Hargassner#4]
Je viens de tester le nouveau code php7, presque tout fonctionne. Dans les étrangetés, j'ai une température de consigne qui varie dans le temps, est-ce normal ou est-ce que c'est parce que ce n'est pas la bonne valeur qui est insérée dans la BDD (cf piece jointe)
![temp-consigne](https://user-images.githubusercontent.com/4292225/95781490-32cca200-0cce-11eb-8a1b-f159115878c3.png)
?

Dans la partie "variables", j'ai aussi quelques bizzarerie. La température de retour est constante et affiche 120°C. Les températures "doit" et "est" pour la zone 2 ne sont pas les bonnes (comme on l'a déjà évoqué), surtout que je n'ai pas de zone2.

Je ne comprends pas bien ce que signifie O², pourrais-tu m'éclairer ?

![erreur-variables](https://user-images.githubusercontent.com/4292225/95782148-8d1a3280-0ccf-11eb-8c32-bb38da04e8f6.png)

Merci pour ton aide et bravo pour la migration ! :)

**Comment by Jahislove** [comment]
alors pour la temperature de consigne ( temperature depart doit ). oui c'est normal
globalement cette courbe varie légèrement en fonction de la temperature exterieure .
les crevasses que tu as a 21h30 , 10h00 et 17h00 correspondent au chauffage de ton Eau Chaude Sanitaire.
ton installateur a activé la priorité ECS , donc pendant l'ECS , le chauffage baisse.
cela permet de chauffer l'eau plus vite et/ou d'avoir assez de puissance pour les petites chaudieres ( c'est le cas de ma 9kw) 

faudrait revoir les reglages de ton ECS  , il est preferable d'avoir 1 seul cycle de chauffe par jour au max
surtout l'été , sinon ta chaudiere va demarrer plusieurs fois par jour pour l'ECS et comme a chaque fois faut qu'elle se rechauffe en premier , ya du gaspillage

les courbes Z2 sont fantaisistes si tu ne possede pas de Z2( il suffit de les désactiver) .
c'est utile uniquement pour les utilisateurs qui en ont une.

la temperature de retour est fausse , effectivement la il y a un soucis , certainement un parametre qui a changé.
il faudrait que tu m'envoi une extraction de ta BDD  sur une journée , que je puisse faire une recherche.

O2 correspond a l'oxygène mesuré par la sonde lambda et est sensé représenter une combustion ideale
c'est le principal parametre utilisé par la chaudiere pour réguler sa combustion 
elle va jouer sur la quantité de bois (%bois) et d'air (vitesse extracteur)pour maintenir cet O2

sinon je t'invite a venir rejoindre la communauté Hargassner sur ce forum , tu pourra y obtenir plus d'info:
https://forums.futura-sciences.com/habitat-bioclimatique-isolation-chauffage/503952-chaudieres-hargassner-regroupement-dinformations-97.html

**Comment by daeavelwyn** [comment]
Salut,

De la matière pour investiguer ! c'est ma BDD sur plusieurs jours. Voici un lien wetransfert pour la télécharger : https://we.tl/t-emOOCK8HmS

Merci pour le lien vers le forum futura-science, je vais aller jeter un oeil !

**Comment by Jahislove** [comment]
alors j'ai vérifié , les parametres du firmware 14k et 14l sont identiques
j'ai vérifié également avec ton extraction des chanels depuis le DAQ
et la temperature retour correspond bien toujours au chanel 23  (TRL) (écrit en colonne c12 de la BDD)
il n'y a donc pas d'erreur dans les graphes. l'explication de ta temperature retour à 120° vient a mon avis du fait que sur ta classic il ne doit pas y avoir de sonde de temerature sur le retour

**Comment by daeavelwyn** [comment]
Ok, je ne tiendrai donc juste pas compte de ces courbes. Merci pour le temps passé à checker ;)
