### ISSUE TITLE
Hargassner

### ISSUE THREAD

**Issue by Superhornet86** [Jahislove/Hargassner#5]
Bonjour nous avons un hargassner aux buches de 1 mètre de long puissance de 72 kw. j'arrive a lire les valeurs de la chaudière avec ton site. mais elle sont pas dans le bon ordre. j'ai apparament une autre version. je voulais savoir comment faire les modification pour que les valeurs ce mets à la bonne place. Je te mets en pièce joint le fichier DAQ de la chaudière avec les diffèrents valeur
[DAQ00000.DAQ.txt](https://github.com/Jahislove/Hargassner/files/5769115/DAQ00000.DAQ.txt)

**Comment by Jahislove** [comment]
Bonjour , 
je m'occupe de rajouter ton firmware avec ton DAQ , laisse moi un peu de temps

**Comment by Jahislove** [comment]
j'ai ajouté ton firmware au logiciel , peut tu le tester avant publication stp . bascule sur la branche firmware10.2h au lieu de master pour la telecharger . tu n'as pas besoin de tout reinstaller , tu as juste besoin de remplacer stockBDD.php , tu pourra réutiliser ton fichier config.inc.php mais n'oublie pas d'y modifier le parametre  firmware en 10.2h

il y a pas mal de  parametres specifique aux buches mais l'essentiel devrait etre la .
 tiens moi au courant

**Comment by Superhornet86** [comment]
Salut je vien d'essayer ta firmware.. il y a quelque valeur qui sont pas juste. j'ai prise quleque photos pour que tu voie les valeur sur la chaudière et sur le site. j'ai pris avant de faire du feux. bonne soiré et encore merci
![2021-01-06 18_24_43-My Hargassner](https://user-images.githubusercontent.com/76995825/103800740-0e722e80-504d-11eb-9a69-668d7064bf81.png)
![2021-01-06 18_24_57-My Hargassner](https://user-images.githubusercontent.com/76995825/103800744-0fa35b80-504d-11eb-94a3-bb2645905ee9.png)
![2021-01-06 18_27_31-config inc php - Bloc-notes](https://user-images.githubusercontent.com/76995825/103800747-103bf200-504d-11eb-9db1-940a2dd81bff.png)
![server hargassner](https://user-images.githubusercontent.com/76995825/103800749-10d48880-504d-11eb-92c0-4d03e86160ee.png)
![IMG_20210106_182316](https://user-images.githubusercontent.com/76995825/103800836-2d70c080-504d-11eb-8825-24e45d343c60.jpg)
![IMG_20210106_182327](https://user-images.githubusercontent.com/76995825/103800840-2f3a8400-504d-11eb-9a04-3bb20fdce6b8.jpg)
![IMG_20210106_182341](https://user-images.githubusercontent.com/76995825/103800843-306bb100-504d-11eb-97d4-2473228200eb.jpg)

**Comment by Jahislove** [comment]
effectivement ya pas mal de parametre qui ne sont pas corrects , par contre il va me falloir plus d'info pour les identifier .
pourrais tu m'envoyer un export de ta BDD , au moins une journée ou la chaudiere a fonctionnée ainsi que des photos des ecrans comme ci dessus mais correspondant a la meme journée
dans phpmyadmin , onglet exporter , au format SQL stp

**Comment by Superhornet86** [comment]
Salut ma base de donnée ne fonction pas sur mon serveur. J'ai synologs ds 718, la partie web est sur le disque dur numéro 2. je suis en php 7.4 est il me semble que j'ai bien suivi tes instruction.

Si tu veux tu pourrais aussi m'expliquer ou je dois aller adapter les paramètres que les valeurs s'affiche juste. 

Dit mois aussi quel information te faut il pour m'aider

merci

**Comment by Jahislove** [comment]
bonjour ,
j'avais oublié de modifier la page d'accueil
j'ai mis a dispo une nouvelle version dans la branche firmware-10.2h
cette fois il te faut tout reinstaller , conserve simplement ton config.inc.cfg

rappel : seule la page d'accueil utilise le telnet , les autres pages utilise la BDD.

pour adapter les parametres , ça ce passe dans json_telnet.php.
si tu fait des modifications , il faudra  me les communiquer car sinon elles seront supprimées a la prochaine mise a jour
