### ISSUE TITLE
Nouveau firmware V14.0m2

### ISSUE THREAD

**Issue by mplok1** [Jahislove/Hargassner#6]
Bonjour,

Je suis en firmware V14.0m2, comment puis je récupérer les fichiers DAQ de la chaudière pour voir les différences avec ton dernier firmware ?

Merci pour ton retour et ton travail.

**Comment by Jahislove** [comment]
bonjour, 
il faut mettre une carte SD dans la chaudiere et faire un export des données , c'est quelque part dans les menu
